source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/aliyun/aliyun-specs.git'

use_frameworks!
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'NoteDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
#pod 'JSONKit-NoWarning',         '~> 1.2'
#pod 'MJRefresh'
#pod 'MJExtension'
pod 'Masonry'
pod 'AFNetworking'
#pod 'YYKit'
#pod 'DMProgressHUD'




  # Pods for NoteDemo

  target 'NoteDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NoteDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
